# Generated by Django 4.0.4 on 2022-05-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polygons',
            fields=[
                ('_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('provider_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('geometry', models.JSONField()),
            ],
            options={
                'ordering': ['_id'],
            },
        ),
    ]
