# Generated by Django 4.0.4 on 2022-05-18 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_polygons'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Polygons',
        ),
    ]
